.eslintrc, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md, package.json
Adds issue and PR templates to GitHub (reference: https://github.com/blog/2111-issue-and-pull-request-templates )
=> PR & Issue templates

README.md
Updates README to secure link.
=> README - Update to secure link

package.json, yarn.lock
Update to the latest and greatest react
=> updated react

src/scripts/docs/examples/DropdownMultiSelectAdvanced.example.txt
Minor changes in multiselect dropdown component example
NA
=> Minor changes in example of multiselect dropdown

src/scripts/components/DropdownCheckbox.jsx
=> adding onClick event to selection label.

dist/scripts/rhinostyle.min.js, src/scripts/components/Date.jsx
Jira Link - 
https://rhinogram.atlassian.net/browse/RHIN-1623
Fix input of undefined error on datepicker dropdown because of ref error.
Not Applicable
=> RHIN-914 : Reverting code to fix datepicker issues

src/less/variables.less
Update variables.less file for old and new value colors in the audit logs page
NA
=> RHIN-2528: Update variables for old and new field values

src/less/dropdowns.less
JIRA link:
https://rhinogram.atlassian.net/browse/RHIN-3080
RhinoPay Manager: UI Adjustments
NA
=> RHIN-3080: RhinoPay Manager: UI Adjustments

src/less/dropdowns.less
Fix Date range Button UI
1. List
=> RHIN-3201: Fix Daterange Button UI

src/scripts/components/VariableMessage.jsx
=> removed checkremoved check for FF

src/scripts/components/VariableMessage.jsx
https://rhinogram.atlassian.net/browse/RHIN-3620
Variable inserts at beginning of input on iOS safari this is because of some existing code, so commenting that code to prevent this to happen.
Variable inserts at beginning of input on ios safari.
=> RHIN-3620: Variable inserts at beginning of input on ios safari

src/scripts/components/Button.jsx
https://rhinogram.atlassian.net/browse/RHIN-3728
Missed out to update the className in 2 places and now updated.
the build was not created properly due to it the changes was not reflecting in rhinofront, so now build was created again
1. List
=> RHIN-3728: Forgot to update className and build again

src/scripts/components/Modal.jsx
Adds the flexibility of passing model container and modal dialog specific props, particularly to address z-index....
=> added class options for modal

src/less/tables.less
https://rhinogram.atlassian.net/browse/RHIN-4218
Mobile web app: Audit Log table grid styles inconsistent
1. List
=> RHIN-4218 Mobile web app: Audit Log table grid styles inconsistent

README.md
=> Added yarn link

src/less/variables.less
Add new Variables for Navigation.
1. List
=> RHIN-4330: Add new variables for Navigation Update

src/less/variables.less
https://rhinogram.atlassian.net/browse/RHIN-4771
adding new analytics colours.
1. List
=> adding analytics colors

src/scripts/components/Select.jsx
https://rhinogram.atlassian.net/browse/RHIN-4448
Right now we are getting one random error on org profile state dropdown so when page loaded but did not have any value selected in dropdown although in database we have state for that org. Even manually things working fine but from Cypress it failed everytime.
1. List
Nothing related to UI change just use updated life cycle react method as we are getting some random issue on org profile
=> RHIN-4448: removing legacy react code from Select component

src/scripts/components/Radio.jsx
PR link: https://rhinogram.atlassian.net/browse/RHIN-5098
Adding data cypress attributes to handle test failure.
Adding data cypress attributes to handle test failure.
1. List
=> RHIN-5098: adding data cypress attributes to avoid test failure.

src/scripts/components/ResourceIntro.jsx
PR link : https://rhinogram.atlassian.net/browse/RHIN-5454
Added data cypress attributes for contact and offices .
Added data cypress attributes for contact and offices .
=> RHIN-5454: Add required data cypress attributes

src/scripts/components/Pill.jsx, src/scripts/components/Resource.jsx
* adds 'data-cypress' attribute to Resource & Pill components to optimize Cypress testing
* adds 'data-cypress' attribute to Resource & Pill components to optimize Cypress testing
=> Rhin 4426/data cypress

src/scripts/components/DropdownCheckbox.jsx, src/scripts/docs/examples/DropdownCheckbox.example.txt
https://rhinogram.atlassian.net/browse/RHIN-5675
Add cypress data attribute
1. List
=> RHIN-5675: add data-attributes for appointment manager- rhinoblast

src/scripts/components/DropdownMultiSelectAdvanced.jsx
Ticket Link: https://rhinogram.atlassian.net/browse/RHIN-5589
Changed the naming format for member in dropdownMultiSelectAdvanced, here sending the memberName as formatted member name from frontend. old format (firstName lastName eg. **Kamal Pandey**) new format (lastName, prefix firstname, suffix eg. **Pandey, Mr. Kamal, Dr**).
Changed the naming format for member in dropdownMultiSelectAdvanced. old format (firstName lastName eg. **Kamal Pandey**) new format (lastName, prefix firstname, suffix eg. **Pandey, Mr. Kamal, Dr**).
1. List
=> RHIN-5589: Member Listing - Make format consistent across the app

src/scripts/components/Alert.jsx, src/scripts/components/Select.jsx
add a prop to the Alert component for cypress data attributes.
=> Support cypress data attribute for the Alert component.

src/scripts/components/NavTabsItem.jsx, src/scripts/components/RhinoSwitch.jsx
**Related Jira link:** 
https://rhinogram.atlassian.net/browse/RHIN-6691
* Data cypress props added for Navlink and Rhinoswitch components
=> Data cypress props added for Navlink and Rhinoswitch components

config/pages.js
**Related Jira link:** [RHIN-XXXX](https://rhinogram.atlassian.net/browse/RHIN-XXXX)
* removes unnecessary import causing conflict when reloading
=> Fixes hot reload
